### ISSUE TITLE
What did I do wrong?

### ISSUE THREAD

**Issue by zapper59** [sentientmachine/erics_vim_syntax_and_color_highlighting#1]
![image](https://cloud.githubusercontent.com/assets/9943931/10155565/84842336-663c-11e5-89f3-d555fa8ca065.png)
It's doing this for html, java, and python, and providing no colors for .sh and javascript.  ":echo g:colors_name" is showing the right theme is being used for each filetype.

**Comment by sentientmachine** [comment]
Hmmm.  Looks like a Christmas tree lol.   The operating system is not right, are you using some strange version of Linux for windows like cygwin or bsd?  If you followed all the instructions it should have worked.  

It looks like the gradients of colors are being flattened to a primary 8 colors.  Not sure how to fix it without access to your box to troubleshoot

**Comment by zapper59** [comment]
Ya it's Mingw.  I think I just configured something wrong because the default color scheme for cpp looks beautiful.  I'll try to track it down and get back to you when I know more.

**Comment by zapper59** [comment]
I've got it working in an actual Linux environment, I'll keep you posted if I ever get it working in Mingw.

**Comment by sentientmachine** [comment]
Awesome thanks, I've often had trouble getting various things working in cygwin or mingw.  I am not very experienced getting into the library requirements for this, I just forked this and tune it to my preferences.  If you figure it out do let me know here and I'll make some edits and notes for the mingw users.
