### ISSUE TITLE
No color schemes for newly created files

### ISSUE THREAD

**Issue by ParceledTongue** [sentientmachine/erics_vim_syntax_and_color_highlighting#2]
Your suggested .vimrc doesn't set a color scheme for newly created files. For example, if I do a <code>vi myjava.java</code>, the editor will have its default color scheme. But if I open it after it exists with <code>vi myjava.java</code>, it will have the <code>monokai</code> color scheme. I don't know if you did this intentionally, but I fixed mine by changing the <code>au BufReadPost</code> lines to <code>au BufNewFile,BufReadPost</code>.

**Comment by sentientmachine** [comment]
Awesome, that's better than what I had, I added it, thanks.
